name: Build
on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "zulu"
      - name: Cache Maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-
      - name: Show versions
        run: |
          java --version
          mvn --version
      - name: Build
        run: mvn install -e
      - name: Prevent generated artifacts from getting cached
        run: rm -rf ~/.m2/repository/com/github/cowwoc/token-bucket